In [1]:
import numpy as np
import pymc3 as pm
import matplotlib.pyplot as plt

%matplotlib inline
plt.style.use('fivethirtyeight')

/usr/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)


In [2]:
p = (np.array([0.1, 0.1, 0.3, 0.3, 0.9, 0.9, 0.0, 0.0, 0.0, 0.0]),
     np.array([0.1, 0.4, 0.3, 0.9, 0.9, 0.3, 0.0, 0.03, 0.0, 0.0]))

y = np.concatenate((np.ones(100, dtype=int), np.zeros(100, dtype=int)))

X = np.zeros((200, 10))
for nn in range(200):
    for ii in range(10):
        X[nn, ii] = np.random.random() < p[y[nn]][ii]

print(y)
print(X)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
model = pm.Model()

with model:
    weight = pm.MvNormal('weight', mu=np.zeros(10), cov=np.identity(10), shape=(10))
    class_prob = 1.0 / (1.0 + np.exp(X.dot(weight)))
    y_obs = pm.Bernoulli('y_obs', p=class_prob, observed=y)

AsTensorError: ('Cannot convert [[Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]\n [Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]\n [Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]\n ...\n [Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]\n [Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]\n [Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 ... Elemwise{true_div,no_inplace}.0\n  Elemwise{true_div,no_inplace}.0 Elemwise{true_div,no_inplace}.0]] to TensorType', <class 'numpy.ndarray'>)

In [ ]:
map_estimate = pm.find_MAP(model=basic_model)

map_estimate

In [8]:
p = (0.8, 0.2)

y = np.concatenate((np.ones(100, dtype=int), np.zeros(100, dtype=int)))

X = np.zeros(200)
for nn in range(200):
    X[nn] = np.random.random() < p[y[nn]]

print(y)
print(X)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1.
 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1.

In [14]:
model = pm.Model()

with model:
    weight = pm.Normal('weight', mu=0, tau=1)
    bias = pm.Normal('bias', mu=0, tau=1)
    class_prob = 1.0 / (1.0 + np.exp(bias + X * weight))
    y_obs = pm.Bernoulli('y_obs', p=class_prob, observed=y)

In [15]:
map_estimate = pm.find_MAP(model=model)

map_estimate

logp = -140.47, ||grad|| = 31.5: 100%|██████████| 9/9 [00:00<00:00, 1657.39it/s]


{'bias': array(-1.17555159), 'weight': array(2.58910482)}

In [13]:
with model:
    # draw 500 posterior samples
    trace = pm.sample()

pm.traceplot(trace)
pm.summary(trace)

AttributeError: 'module' object has no attribute 'cpu_count'